### PR TITLE
Support for DuckDB v1.1.0

### LINKED ISSUE #21: Support for DuckDB v1.1.0
Writing to notify that at this moment in time this extension do not successfully build or test against duckdb v1.1.0.

I am writing to inform you that the extension keep being available on duckdb v1.0.0, but can't be distributed on v1.1.0 until the problem is sorted out.

Problem, as detected by the build infrastructure is as follow: https://github.com/duckdb/community-extensions/actions/runs/10619930977/job/29438634772#step:15:4420, and looks to require to adapt to some duckdb-level API changes
```
In file included from /Users/runner/work/community-extensions/community-extensions/src/storage/bigquery_insert.cpp:17:
Error: /Users/runner/work/community-extensions/community-extensions/src/include/storage/bigquery_insert.hpp:47:12: error: virtual function 'ParamsToString' has a different return type ('string' (aka 'basic_string<char>')) than the function it overrides (which has return type 'InsertionOrderPreservingMap<string>' (aka 'InsertionOrderPreservingMap<basic_string<char>>'))
    string ParamsToString() const override;
    ~~~~~~ ^
/Users/runner/work/community-extensions/community-extensions/duckdb/src/include/duckdb/execution/physical_operator.hpp:64:46: note: overridden virtual function is here
        virtual InsertionOrderPreservingMap<string> ParamsToString() const {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
[317/509] Building CXX object src/common/CMakeFiles/duckdb_common.dir/ub_duckdb_common.cpp.o
[318/509] Building CXX object src/core_functions/aggregate/holistic/CMakeFiles/duckdb_aggr_holistic.dir/ub_duckdb_aggr_holistic.cpp.o
ninja: build stopped: subcommand failed.
```

If you can use assistance, please circle back on this.

More information / example of what other extension needed to change at https://github.com/duckdb/community-extensions/issues/85.

Thanks for being involved with the duckdb community extensions!

### PR DESCRIPTION
**Pull request by jankramer**
This should fix #21

### CODE REVIEW

**Comment by hafenkran** [comment]
Oh hey @jankramer, thanks a lot for the PR! Unfortunately, it is currently a bit redundant since I implemented the update fix yesterday (along some other stuff). I just haven’t had a chance to fully test it or address the GitHub Actions pipeline issue yet — it got pretty late last night. However, I also noticed that in your PR, the duckdb_version in MainDistributionPipeline.yml is still set to duckdb v1.0.0. This would hinder the project to build right now.

**Comment by jankramer** [comment]
Gotcha, I'll leave it to you then 👍

**Comment by hafenkran** [comment]
merged it to an intermediate branch.

**Comment by jankramer** [comment]
Awesome! Thanks for your work on this extension, it's really nice 👍 I'll certainly give it a star 😄

**Pull request merged**
