### PR TITLE
Add the possibility to fetch results of arbitrary SQL queries.

### PR DESCRIPTION
**Pull request by jrosskopf**
This simple addition makes minimal changes to the `bigquery_scan` function. 

- It combines the already existing functionality for query execution with the scan functionality
- It executes a BigQuery statement, typically `SELECT`, and get the temporary destination table from the job.
- Then it executes exactly the same logic as a normal table scan

This makes it possible to also read from views. (It is a workaround to query arbitrary BigQuery objects also used e.g. by the Spark BQ connector).

Open points: 
- [x]  Not sure how to handle testing? Can you maybe give advice.
- [x]  The destination table is temporary. However, should there be cleanup with explicit delete happening after the scan?

### CODE REVIEW

**Comment by hafenkran** [comment]
Hey @jrosskopf, many thanks a lot for the PR!

This was actually something I had on my bucket list as well, so let's get it merged. The implementation looks good, but I do have a few notes though:

* You usually could define a `destination_table` to allow for the results to be stored permanently instead of using an anonymous temp table. Maybe you can add that to the named parameters as an option. 
* Please add some tests (see comment below)
* (Rather a point for discussion): While the name `bigquery_query` is semantically appropriate, I just feel like users might be drawn to this function immediately because of the name. In my perspective, the query functionality feels more like a fallback or alternative to the primary scan function. Maybe there's another name that fits better? Or perhaps this is just my feeling. And/Or the documentation needs to make it 100% clear, that the most efficient way is to do a scan.

> Open points:
> 
> * [ ]   Not sure how to handle testing? Can you maybe give advice.
You can create a simple table, insert some entries, create a view with `bigquery_execute`, read from that view using `bigquery_query`, and validate the expected result. In my point of view, it covers the whole functionality. Just follow a basic example from the `sql/test/bigquery` folder to get started. Similarly for the `destination_table` option with reading a second time from the `destination_table`. 

> * [ ]   The destination table is temporary. However, should there be cleanup with explicit delete happening after the scan?
As far as I know, you can't delete those anonymous temporary tables. They're automatically cleaned up after a while (~24 hours or so?).

Let me know what you think!

**Comment by jrosskopf** [comment]
Okay, so did a little bit of research in the docs [Using cached query results](https://cloud.google.com/bigquery/docs/cached-results?authuser=1). So @hafenkran, you are totally right . The lifespan of this temporary result table is typically around 24 hours, with following properties:

- The default cache lifetime for query results is approximately 24 hour. After this period, the cached results expire and are no longer accessible.
- However, it's important to note that the 24-hour lifetime is best-effort and not guaranteed. The cached results may be invalidated sooner than 24 hours in some cases.
- These temporary result tables are stored in special hidden datasets called "anonymous datasets". Access to these datasets is restricted to the owner - the user who ran the query that produced the cached result.
- There are no storage costs associated with these temporary, cached result tables.
- It's worth noting that attempting to access these temporary tables after their expiration (which typically occurs around the 24-hour mark) will result in a "Table not found" error

**Comment by hafenkran** [comment]
Thanks a lot for the clarification. I was a bit unsure about the costs and this is definitely good to know.

**Comment by jrosskopf** [comment]
I had a look how to implement the `destination_table` functionality. Unfortunately it seems to be not possible to set the destination via the `job_client.Query` API. Instead, one has to use `job_client.Insert`. This would be a somewhat more impactfull change. 

So go with the easy way, without destination? Or change `ExectueQuery` to use `job_client.Insert`?

**Comment by hafenkran** [comment]
Ah, yeah makes sense. Let's go for the easy way.
Thanks for checking!

**Comment by jrosskopf** [comment]
@hafenkran, added test case and renamed `bigquery_query` to `bigquery_select`.

**Comment by hafenkran** [comment]
LGTM! I'll change the MR to develop and merge it to the main on the weekend.

**Comment by jrosskopf** [comment]
@hafenkran Do you have an estimate when you can merge this change to main? (We really look forward to pull the extension from community extensions)

**Comment by hafenkran** [comment]
Hey @jrosskopf, sorry for the delay. I just wanted to finalize a few things with the release and update the README accordingly. My goal is to make a release this weekend.

However, I also have a small request (if you're up for it). After some discussions, I just decided to rename the command back to `bigquery_query` for consistency with other extensions. For instance, the [mysql_scanner](https://duckdb.org/docs/extensions/mysql.html#the-mysql_query-table-function) and the [postgres_scanner](https://duckdb.org/docs/extensions/postgres.html#the-postgres_query-table-function) use a `*_query` naming pattern for those queries. If you're up for it, feel free to make the adjustment today and create a MR. Otherwise, I'm happy to take care of it. I'll also make sure to clearly explain the differences in the documentation.

**Pull request merged**
